module FHIR
  class ExplanationOfBenefit < DomainResource
    include Mongoid::Document
    field :typeName, type: String, default: 'ExplanationOfBenefit'
    embeds_many :identifier, class_name: 'Identifier'
    embeds_one :status, class_name: 'ExplanationOfBenefitStatus'
    embeds_one :type, class_name: 'CodeableConcept'
    embeds_one :subType, class_name: 'CodeableConcept'
    embeds_one :use, class_name: 'Use'
    embeds_one :patient, class_name: 'Reference'
    embeds_one :billablePeriod, class_name: 'Period'
    field :created, type:  # primitive
    embeds_one :_created, class_name: 'Extension'
    embeds_one :enterer, class_name: 'Reference'
    embeds_one :insurer, class_name: 'Reference'
    embeds_one :provider, class_name: 'Reference'
    embeds_one :priority, class_name: 'CodeableConcept'
    embeds_one :fundsReserveRequested, class_name: 'CodeableConcept'
    embeds_one :fundsReserve, class_name: 'CodeableConcept'
    embeds_many :related, class_name: 'ExplanationOfBenefitRelated'
    embeds_one :prescription, class_name: 'Reference'
    embeds_one :originalPrescription, class_name: 'Reference'
    embeds_one :payee, class_name: 'ExplanationOfBenefitPayee'
    embeds_one :referral, class_name: 'Reference'
    embeds_one :facility, class_name: 'Reference'
    embeds_one :claim, class_name: 'Reference'
    embeds_one :claimResponse, class_name: 'Reference'
    embeds_one :outcome, class_name: 'RemittanceOutcome'
    field :disposition, type:  # primitive
    embeds_one :_disposition, class_name: 'Extension'
    field :preAuthRef, type: Array # primitive
    embeds_many :_preAuthRef, class_name: 'Extension'
    embeds_many :preAuthRefPeriod, class_name: 'Period'
    embeds_many :careTeam, class_name: 'ExplanationOfBenefitCareTeam'
    embeds_many :supportingInfo, class_name: 'ExplanationOfBenefitSupportingInfo'
    embeds_many :diagnosis, class_name: 'ExplanationOfBenefitDiagnosis'
    embeds_many :procedure, class_name: 'ExplanationOfBenefitProcedure'
    field :precedence, type:  # primitive
    embeds_one :_precedence, class_name: 'Extension'
    embeds_many :insurance, class_name: 'ExplanationOfBenefitInsurance'
    embeds_one :accident, class_name: 'ExplanationOfBenefitAccident'
    embeds_many :item, class_name: 'ExplanationOfBenefitItem'
    embeds_many :addItem, class_name: 'ExplanationOfBenefitAddItem'
    embeds_many :adjudication, class_name: 'ExplanationOfBenefitItemAdjudication'
    embeds_many :total, class_name: 'ExplanationOfBenefitTotal'
    embeds_one :payment, class_name: 'ExplanationOfBenefitPayment'
    embeds_one :formCode, class_name: 'CodeableConcept'
    embeds_one :form, class_name: 'Attachment'
    embeds_many :processNote, class_name: 'ExplanationOfBenefitProcessNote'
    embeds_one :benefitPeriod, class_name: 'Period'
    embeds_many :benefitBalance, class_name: 'ExplanationOfBenefitBenefitBalance'
  end
end
