name: Publish Gem

on:
  push:
    branches:
      - "*"
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4

      - name: Install bundler & bundle-audit
        run: |
          gem install bundler -v 2.1.4
          gem install bundle-audit

      - name: Install ruby gems
        run: bundle install --jobs 4 --retry 3

      - name: Build and test with Rake
        env:
          RAILS_ENV: test
        run: |
          bundle exec rubocop
          bundle exec bundle-audit update && bundle exec bundle-audit check
          bundle exec rake

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
